### ISSUE TITLE
Engine Professional Tab - New Subscribers

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#62]
Sagar,
When I filter New Subscribers in the Engine Professional portion of our MMS program I get these two records. I cannot update, save, or delete them. No matter what I do they stay in this section with the same data. Can you see what's going on?

![image](https://user-images.githubusercontent.com/26386841/211408006-d7fc62f6-86f1-402f-9d2a-2d1822a2ab99.png)

**Comment by SagarPC** [comment]
@amandagoyette  We are looking into this issue and will send you update as soon as possible.

**Comment by SagarPC** [comment]
@amandagoyette  We fixed this issue and uploaded on live. There was an issue because of "Receive Magazine Type" value not selected.  We updated code and now we are considering "Paper" as default value if it's not selected. 

Please check and let us know if any change required.

![image](https://user-images.githubusercontent.com/31076567/211806015-cd50fa38-d7b8-401f-9e95-8eb1aa12915e.png)

**Comment by amandagoyette** [comment]
That worked thank you!
